[package]
name = "analiza-treningov"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "analiza-treningov"
path = "src/main.rs"

[lib]
name = "analiza_treningov"
path = "src/lib.rs"


[dependencies]
fitparser = "0.10"
flate2 = "*"
csv = "*"
serde = { version = "*", features = ["derive"] }
chrono = "*"
rayon = "*"
